name: eeg_visualizer_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Camera and Audio - Updating record to a new major version to fix dependencies
  camera: ^0.11.0+1
  record: ^6.0.0

  # State Management
  provider: ^6.1.2

  # BLE & Permissions
  permission_handler: ^11.3.1
  location: ^6.0.2
  flutter_blue_plus: ^1.32.4

  # Data processing & Utils
  zstandard: ^1.3.27
  http: ^1.2.1
  intl: ^0.19.0

  # UI
  fl_chart: ^1.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

